name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Building and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            clang \
            clang-tidy \
            clang-format

      - name: Clean build
        run: rm -rf build

      - name: Configure (CMake)
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -- -j2

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --verbose --extra-verbose

      - name: Clang-Format
        run: clang-format -i include/bp/*.hpp

      - name: Clang-Tidy check
        run: clang-tidy -p build include/bp/*.hpp --config-file=.clang-tidy --warnings-as-errors=* || true
